name: 'Site Name'
email: 'your_email@domain.com'
description: >
  A description of your website, use the same one as you use within your package description! (Note; Use > for multi-line descriptions).

source: ./src
destination: ./dist

include:
  - '_pages'

keep_files:
  - 'css/'
  - 'img/'
  - 'js/'
  - 'app.js'

strict_front_matter: true

incremental: true

url: 'http://localhost:8080/'

permalink: pretty
timezone: Europe/London

title: Matthew Birch
